name: "Publish to pypi"
on:
  push:
    tags:
      - "v*"
env:
  PYTHON_VERSION: "3.10"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - {name: "Checkout", uses: actions/checkout@v3}
      - name: "Set up Python ${{ env.PYTHON_VERSION }}"
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: "Set up python dependencies"
        run: |
          set -eu
          pip install --upgrade 'pip~=23'
          pip install --upgrade 'build~=0.9.0' 'twine~=4.0.1'
      - name: Build
        run: |
          set -eu
          python -m build
      - name: Upload
        run: |
          set -eu
          TWINE_PASSWORD="${{ secrets.PYPI_TOKEN }}" twine upload --repository="https://upload.pypi.org/legacy/" --username="__token__" dist/*
